# Generated by Django 2.1.2 on 2018-12-11 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20181211_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('folio_or', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_or', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_termino', models.DateTimeField()),
                ('id_ascensor', models.IntegerField()),
                ('modelo_ascensor', models.CharField(max_length=100)),
                ('fallos_detectados', models.TextField(max_length=100)),
                ('reparaciones_or', models.TextField(max_length=100)),
                ('piezas_or', models.TextField(max_length=100)),
                ('cliente_or', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('nom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
