# Generated by Django 2.1.2 on 2018-12-12 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='tecnico',
        ),
        migrations.AlterField(
            model_name='orden',
            name='hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orden',
            name='hora_termino',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
