# Generated by Django 2.1.2 on 2018-12-13 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181212_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_or',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
